name: CI_Linux

on:
  pull_request:
    branches:
    - 3.x
    - my/3.x

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.5.0
      with:
        access_token: ${{ github.token }}
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 3
    - name: Setup environment
      run: |
        sudo bash ./build/ci/linux/setup.sh
    - name: Build
      run: |
        sudo bash ./build/ci/linux/build.sh -n ${{ github.run_id }} --telemetry ${{ secrets.TELEMETRY_TRACK_ID }} 
    - name: Package 
      run: |
        sudo bash ./build/ci/linux/package.sh
    - name: Publish package
      run: |
        sudo bash ./build/ci/linux/publish.sh -s ${{ secrets.OSUOSL_SSH_ENCRYPT_SECRET }} 
    - name: Upload artifacts on GitHub
      uses: actions/upload-artifact@v2
      with:
        name: MuseScore_${{ github.run_id }}
        path: ./build.artifacts/    
